/**
 * Mock repository data for PAGE 4 — Knowledge Repository
 * 
 * IMPORTANT: This is demo/fictional data for frontend development purposes only.
 * Do not use this data for any real research, policy, or government purposes.
 * All institutions, document titles, and statistics are representative examples.
 */

export type ContentType = 
  | "Research Paper"
  | "Policy Document"
  | "Legal Document"
  | "Case Study"
  | "Dataset"
  | "Report";

export type Theme = 
  | "Climate & Land"
  | "Urbanization"
  | "Land Disputes"
  | "Sustainable Land-Use Planning"
  | "Geospatial Governance"
  | "Digital Transformation"
  | "Tenure Security"
  | "Legal Framework";

export type AccessTier = "Public" | "Restricted" | "Government-Only";

export interface RepositoryDocument {
  id: string;
  title: string;
  contentType: ContentType;
  description: string;
  summary: string;
  author: string;
  institution: string;
  publishedAt: string;
  createdAt: string;
  updatedAt: string;
  theme: Theme;
  state: string;
  district?: string;
  language: string;
  accessTier: AccessTier;
  views?: number;
  downloads?: number;
  citations?: number;
  thumbnail?: string;
  featured?: boolean;
}

export const MOCK_REPOSITORY_DATA: RepositoryDocument[] = [
  {
    id: "1",
    title: "Impact of Land Ceiling Reforms on Urban Housing Supply: A Multi-State Analysis",
    contentType: "Research Paper",
    description: "Comprehensive analysis of land ceiling repeal effects across 5 major states with housing market data",
    summary: "This study examines the impact of land ceiling reforms on urban housing supply across five Indian states. Using econometric analysis of housing market data from 2010-2023, we find that reform implementation correlates with a 15-20% increase in new housing starts in metropolitan areas.",
    author: "Dr. Priya Sharma",
    institution: "National Institute of Public Finance and Policy",
    publishedAt: "2024-03-15",
    createdAt: "2024-03-15",
    updatedAt: "2024-03-15",
    theme: "Urbanization",
    state: "Maharashtra",
    district: "Mumbai",
    language: "English",
    accessTier: "Public",
    views: 1243,
    downloads: 456,
    citations: 23,
    featured: true,
  },
  {
    id: "2",
    title: "Climate Vulnerability Assessment of Coastal Land Systems in Eastern India",
    contentType: "Research Paper",
    description: "Satellite-based analysis of coastal erosion patterns and climate risk zones in eastern coastal states",
    summary: "Using satellite imagery and climate modeling, this assessment identifies high-vulnerability coastal zones in Odisha, West Bengal, and Andhra Pradesh. The study provides risk maps and recommends adaptation strategies for coastal land management.",
    author: "Dr. Rajesh Kumar",
    institution: "ISRO & Ministry of Environment",
    publishedAt: "2024-02-20",
    createdAt: "2024-02-20",
    updatedAt: "2024-02-20",
    theme: "Climate & Land",
    state: "Odisha",
    language: "English",
    accessTier: "Public",
    views: 892,
    downloads: 321,
    citations: 18,
    featured: true,
  },
  {
    id: "3",
    title: "Digital Land Records Implementation: Comparative Study of State Experiences",
    contentType: "Report",
    description: "Comparative analysis of digital land record systems across 12 states with implementation lessons",
    summary: "This report compares digital land record implementation across 12 Indian states, analyzing technical approaches, adoption rates, and challenges. It provides a framework for successful digital transformation in land administration.",
    author: "NITI Aayog Research Team",
    institution: "NITI Aayog",
    publishedAt: "2024-01-10",
    createdAt: "2024-01-10",
    updatedAt: "2024-01-10",
    theme: "Digital Transformation",
    state: "Delhi",
    language: "English",
    accessTier: "Public",
    views: 1567,
    downloads: 678,
    citations: 45,
    featured: true,
  },
  {
    id: "4",
    title: "Land Dispute Resolution Mechanisms: Evidence from District Courts",
    contentType: "Legal Document",
    description: "Analysis of land dispute patterns and resolution times from district court records across 8 states",
    summary: "Based on district court records from 8 states, this study analyzes patterns in land dispute types, resolution times, and outcomes. It identifies systemic bottlenecks and recommends procedural reforms to reduce litigation backlog.",
    author: "Prof. Amitabh Singh",
    institution: "National Law University, Delhi",
    publishedAt: "2024-04-05",
    createdAt: "2024-04-05",
    updatedAt: "2024-04-05",
    theme: "Land Disputes",
    state: "Delhi",
    language: "English",
    accessTier: "Restricted",
    views: 756,
    downloads: 234,
    citations: 12,
    featured: false,
  },
  {
    id: "5",
    title: "Sustainable Land-Use Planning Framework for Semi-Arid Regions",
    contentType: "Policy Document",
    description: "Policy framework for sustainable land-use planning in semi-arid regions with climate adaptation strategies",
    summary: "This policy framework provides guidelines for sustainable land-use planning in semi-arid regions of India. It integrates climate adaptation, water resource management, and agricultural productivity considerations into a comprehensive planning approach.",
    author: "Ministry of Rural Development",
    institution: "Government of India",
    publishedAt: "2024-03-01",
    createdAt: "2024-03-01",
    updatedAt: "2024-03-01",
    theme: "Sustainable Land-Use Planning",
    state: "Rajasthan",
    language: "English",
    accessTier: "Public",
    views: 1102,
    downloads: 445,
    citations: 31,
    featured: false,
  },
  {
    id: "6",
    title: "Geospatial Dataset: Land Use Classification for Karnataka (2020-2023)",
    contentType: "Dataset",
    description: "High-resolution land use classification dataset for Karnataka derived from satellite imagery",
    summary: "This dataset provides high-resolution land use classification for Karnataka state from 2020-2023, derived from Sentinel-2 satellite imagery. Includes 15 land use classes with 92% overall accuracy.",
    author: "Data Processing Team",
    institution: "Bhuvan-ISRO",
    publishedAt: "2024-02-15",
    createdAt: "2024-02-15",
    updatedAt: "2024-02-15",
    theme: "Geospatial Governance",
    state: "Karnataka",
    language: "English",
    accessTier: "Public",
    views: 2341,
    downloads: 892,
    citations: 67,
    featured: true,
  },
  {
    id: "7",
    title: "Tenure Security and Agricultural Investment: Evidence from Field Surveys",
    contentType: "Research Paper",
    description: "Empirical study examining relationship between land tenure security and agricultural investment decisions",
    summary: "Based on field surveys across 6 states, this study examines how land tenure security affects agricultural investment decisions. Findings show that secure tenure increases long-term agricultural investments by 35% on average.",
    author: "Dr. Meera Krishnan",
    institution: "Indian Council of Agricultural Research",
    publishedAt: "2024-01-25",
    createdAt: "2024-01-25",
    updatedAt: "2024-01-25",
    theme: "Tenure Security",
    state: "Punjab",
    language: "English",
    accessTier: "Public",
    views: 987,
    downloads: 378,
    citations: 28,
    featured: false,
  },
  {
    id: "8",
    title: "Urban Land Market Analysis: Price Trends and Affordability Indices",
    contentType: "Dataset",
    description: "Comprehensive dataset of urban land prices and affordability indices for 50 major cities",
    summary: "This dataset contains urban land price trends and affordability indices for 50 major Indian cities from 2015-2023. Includes transaction-level data, price per square meter, and housing affordability metrics.",
    author: "Urban Economics Division",
    institution: "Reserve Bank of India",
    publishedAt: "2024-03-20",
    createdAt: "2024-03-20",
    updatedAt: "2024-03-20",
    theme: "Urbanization",
    state: "Maharashtra",
    language: "English",
    accessTier: "Restricted",
    views: 1876,
    downloads: 654,
    citations: 52,
    featured: false,
  },
  {
    id: "9",
    title: "Case Study: Successful Land Consolidation in Agricultural Zones",
    contentType: "Case Study",
    description: "Documented case study of successful land consolidation programs in Punjab and Haryana",
    summary: "This case study examines successful land consolidation programs implemented in Punjab and Haryana. It analyzes the institutional mechanisms, stakeholder participation, and productivity outcomes of these programs.",
    author: "State Agriculture Department",
    institution: "Government of Punjab",
    publishedAt: "2024-02-28",
    createdAt: "2024-02-28",
    updatedAt: "2024-02-28",
    theme: "Sustainable Land-Use Planning",
    state: "Punjab",
    language: "English",
    accessTier: "Public",
    views: 654,
    downloads: 234,
    citations: 15,
    featured: false,
  },
  {
    id: "10",
    title: "Digital Transformation of Land Administration: Implementation Guidelines",
    contentType: "Policy Document",
    description: "Official guidelines for digital transformation of land administration at state and district levels",
    summary: "These official guidelines provide a comprehensive framework for digital transformation of land administration. They cover technical standards, process reengineering, capacity building, and change management for successful implementation.",
    author: "Department of Land Resources",
    institution: "Government of India",
    publishedAt: "2024-04-01",
    createdAt: "2024-04-01",
    updatedAt: "2024-04-01",
    theme: "Digital Transformation",
    state: "Delhi",
    language: "English",
    accessTier: "Government-Only",
    views: 432,
    downloads: 156,
    citations: 8,
    featured: false,
  },
  {
    id: "11",
    title: "Climate-Smart Agriculture: Land Management Practices for Resilience",
    contentType: "Research Paper",
    description: "Research on climate-smart agricultural land management practices in drought-prone regions",
    summary: "This research evaluates climate-smart agricultural land management practices in drought-prone regions of Maharashtra and Karnataka. It identifies practices that improve resilience while maintaining productivity under climate stress.",
    author: "Dr. Anand Patel",
    institution: "Central Research Institute for Dryland Agriculture",
    publishedAt: "2024-03-10",
    createdAt: "2024-03-10",
    updatedAt: "2024-03-10",
    theme: "Climate & Land",
    state: "Maharashtra",
    language: "English",
    accessTier: "Public",
    views: 789,
    downloads: 312,
    citations: 21,
    featured: false,
  },
  {
    id: "12",
    title: "Land Governance Index: Methodology and State Rankings (2024)",
    contentType: "Report",
    description: "Annual report on land governance performance across Indian states with methodology and rankings",
    summary: "This annual report presents the Land Governance Index for 2024, ranking Indian states on land administration efficiency, transparency, and service delivery. The methodology combines quantitative metrics and qualitative assessments.",
    author: "Land Governance Research Team",
    institution: "Centre for Policy Research",
    publishedAt: "2024-04-10",
    createdAt: "2024-04-10",
    updatedAt: "2024-01-10",
    theme: "Digital Transformation",
    state: "Delhi",
    language: "English",
    accessTier: "Public",
    views: 2134,
    downloads: 789,
    citations: 89,
    featured: true,
  },
  {
    id: "13",
    title: "Geospatial Analysis of Forest Land Conversion Patterns",
    contentType: "Dataset",
    description: "Dataset showing forest land conversion patterns and drivers across central Indian states",
    summary: "This dataset analyzes forest land conversion patterns across central Indian states from 2010-2023. It identifies conversion drivers, spatial patterns, and provides GIS layers for further analysis.",
    author: "Forest Survey Division",
    institution: "Ministry of Environment, Forest and Climate Change",
    publishedAt: "2024-02-05",
    createdAt: "2024-02-05",
    updatedAt: "2024-02-05",
    theme: "Geospatial Governance",
    state: "Madhya Pradesh",
    language: "English",
    accessTier: "Restricted",
    views: 1023,
    downloads: 423,
    citations: 34,
    featured: false,
  },
  {
    id: "14",
    title: "Legal Framework for Land Acquisition: Comparative Analysis",
    contentType: "Legal Document",
    description: "Comparative analysis of land acquisition laws across states with recommendations for harmonization",
    summary: "This legal document provides a comparative analysis of land acquisition laws across Indian states. It identifies variations in compensation mechanisms, rehabilitation provisions, and procedural requirements, with recommendations for harmonization.",
    author: "Legal Research Cell",
    institution: "National Law School of India University",
    publishedAt: "2024-01-15",
    createdAt: "2024-01-15",
    updatedAt: "2024-01-15",
    theme: "Land Disputes",
    state: "Karnataka",
    language: "English",
    accessTier: "Public",
    views: 567,
    downloads: 198,
    citations: 11,
    featured: false,
  },
  {
    id: "15",
    title: "Urban Expansion and Agricultural Land Loss: Satellite Analysis",
    contentType: "Research Paper",
    description: "Satellite-based analysis of urban expansion patterns and agricultural land conversion around major cities",
    summary: "Using satellite imagery from 2000-2023, this study analyzes urban expansion patterns and agricultural land conversion around 10 major Indian cities. It quantifies agricultural land loss and identifies spatial patterns of urban growth.",
    author: "Dr. Sunita Rao",
    institution: "Indian Institute of Technology, Bombay",
    publishedAt: "2024-03-25",
    createdAt: "2024-03-25",
    updatedAt: "2024-03-25",
    theme: "Urbanization",
    state: "Maharashtra",
    language: "English",
    accessTier: "Public",
    views: 1456,
    downloads: 534,
    citations: 42,
    featured: false,
  },
  {
    id: "16",
    title: "Tenure Security for Women Landholders: Policy Analysis",
    contentType: "Policy Document",
    description: "Analysis of women's land tenure security across states with policy recommendations",
    summary: "This policy document analyzes women's land tenure security across Indian states, examining legal frameworks, implementation gaps, and socio-economic barriers. It provides evidence-based recommendations for improving women's land rights.",
    author: "Gender and Land Rights Unit",
    institution: "Ministry of Rural Development",
    publishedAt: "2024-02-10",
    createdAt: "2024-02-10",
    updatedAt: "2024-02-10",
    theme: "Tenure Security",
    state: "Delhi",
    language: "English",
    accessTier: "Public",
    views: 876,
    downloads: 345,
    citations: 25,
    featured: false,
  },
  {
    id: "17",
    title: "District-Level Land Records Database: Sample Data",
    contentType: "Dataset",
    description: "Sample dataset of district-level land records with ownership and transaction information",
    summary: "This sample dataset contains anonymized district-level land records with ownership information, transaction history, and land use classifications. It serves as a reference for researchers studying land administration systems.",
    author: "Data Governance Division",
    institution: "National Informatics Centre",
    publishedAt: "2024-01-20",
    createdAt: "2024-01-20",
    updatedAt: "2024-01-20",
    theme: "Digital Transformation",
    state: "Uttar Pradesh",
    language: "English",
    accessTier: "Government-Only",
    views: 321,
    downloads: 145,
    citations: 6,
    featured: false,
  },
  {
    id: "18",
    title: "Case Study: Community Land Rights in Tribal Areas",
    contentType: "Case Study",
    description: "Documented case study of community land rights recognition and implementation in tribal areas",
    summary: "This case study examines the implementation of community land rights recognition in tribal areas of Odisha and Jharkhand. It analyzes the legal framework, implementation challenges, and outcomes for tribal communities.",
    author: "Tribal Affairs Research Team",
    institution: "Ministry of Tribal Affairs",
    publishedAt: "2024-03-05",
    createdAt: "2024-03-05",
    updatedAt: "2024-03-05",
    theme: "Land Disputes",
    state: "Odisha",
    language: "English",
    accessTier: "Public",
    views: 543,
    downloads: 212,
    citations: 14,
    featured: false,
  },
  {
    id: "19",
    title: "GIS-Based Land Use Planning Tool: Technical Documentation",
    contentType: "Report",
    description: "Technical documentation for GIS-based land use planning tool with user guide and implementation guide",
    summary: "This technical documentation provides comprehensive guidance for using the GIS-based land use planning tool. It includes user manuals, technical specifications, and implementation guidelines for state and district officials.",
    author: "GIS Development Team",
    institution: "Bhuvan-ISRO",
    publishedAt: "2024-04-15",
    createdAt: "2024-04-15",
    updatedAt: "2024-04-15",
    theme: "Geospatial Governance",
    state: "Karnataka",
    language: "English",
    accessTier: "Public",
    views: 765,
    downloads: 298,
    citations: 19,
    featured: false,
  },
  {
    id: "20",
    title: "Land Dispute Resolution: Alternative Dispute Resolution Mechanisms",
    contentType: "Research Paper",
    description: "Research on effectiveness of alternative dispute resolution mechanisms for land disputes",
    summary: "This research evaluates the effectiveness of alternative dispute resolution (ADR) mechanisms for land disputes in Karnataka and Andhra Pradesh. It compares ADR outcomes with traditional court-based resolution in terms of time, cost, and satisfaction.",
    author: "Dr. Venkatesh Iyer",
    institution: "National Law School of India University",
    publishedAt: "2024-02-25",
    createdAt: "2024-02-25",
    updatedAt: "2024-02-25",
    theme: "Land Disputes",
    state: "Karnataka",
    language: "English",
    accessTier: "Public",
    views: 654,
    downloads: 267,
    citations: 17,
    featured: false,
  },
];

export const CONTENT_TYPES: ContentType[] = [
  "Research Paper",
  "Policy Document",
  "Legal Document",
  "Case Study",
  "Dataset",
  "Report",
];

export const THEMES: Theme[] = [
  "Climate & Land",
  "Urbanization",
  "Land Disputes",
  "Sustainable Land-Use Planning",
  "Geospatial Governance",
  "Digital Transformation",
  "Tenure Security",
  "Legal Framework",
];

export const STATES = [
  "Maharashtra",
  "Karnataka",
  "Uttar Pradesh",
  "Madhya Pradesh",
  "Rajasthan",
  "Punjab",
  "Haryana",
  "Odisha",
  "West Bengal",
  "Andhra Pradesh",
  "Delhi",
  "Tamil Nadu",
  "Gujarat",
  "Kerala",
  "Telangana",
];

export const LANGUAGES = [
  "English",
  "Hindi",
  "Tamil",
  "Telugu",
  "Kannada",
  "Malayalam",
  "Marathi",
  "Bengali",
  "Gujarati",
  "Punjabi",
];

export const ACCESS_TIERS: AccessTier[] = ["Public", "Restricted", "Government-Only"];
